---
# file: practice/2.application-abstractions/2.replicaset/replicaset.yaml
apiVersion: apps/v1 # Очень важная строчка, всегда нужно понимать что откуда брать!!!! ИЗУЧИТЬ!!!!
kind: ReplicaSet # обьект представляет себя набор реплик приложений
metadata:
  name: my-replicaset
spec:
  replicas: 2  # Указываем кол-во нужных нам реплик с данным приложением
  selector:
    matchLabels: # Искать все поды которые имеют  лейлы которые укажем ниже, здесь это my-app
      app: my-app 
  template: # Этот параметр ознчает с какими настройками будут создаваться поды 
    metadata:
      labels: # Важный параметр для пода-реплики, по этому лейьблу будут в дальнейшем искаться копии данного приложения
        app: my-app
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        ports:
        - containerPort: 80
...


# C:\Windows\system32> minikube start --driver=hyperv
# Чтоб увеличить колличество реплик какого то приложения надо выполнить команду
#  kubectl.exe scale --replicas 2 replicaset my-replicaset, где


# --replicas 2 это на сколько надо увеличить, то есть с текущего значения + то которое указал
# replicaset это параметр 
# my-replicaset это то приложение которое вы хотите увеличить , его можно посмотреть в metadata name:
# Также данная команда поддерживает увеличение как в большую сторону так и удаление не нужных реплик, тоже самая команда только вместо суммирование реплик он вычитает то колличество которое указали
# для примера, ранее у нас было 4 реплики и нам надо уменьшить до двух то просто указываем replicas 2 то есть сугубо будет выполнена команда 4-2(общее кол-во реплик минус то что указали )
# -----------------------------------

# Обновление образа в контейнере 
# Для этого выполняется команда kubectl set image replicaset my-replicaset nginx=quay.io/testing-farm/nginx:1.13
# где

# my-replicaset имя нашего контейнера
# так как в поде может быть несколько контейнеров и чтоб поменя у определенного нам нужно указать имя контейнера
# nginx и далее через = указываем новый образ
# Если все прошло успешно то мы увидем вот такое сообшщение replicaset.apps/my-replicaset image updated
# -----------------------------------

# обьяснения самого кубера по повлоду того или иного 
# kubectl explain pod
# проверка определенного пункта 
# kubectl explain pod.spec







