---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        envFrom:
        - configMapRef:
            name: my-configmap-env
        env:
        - name: TEST
          value: foo
        - name: TEST_1
          valueFrom:
            secretKeyRef:
              name: test
              key: test1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
...

# Чтоб создать свою секрет надо выполнить команду 
# kubectl create secret generic test --from-literal=test1=asdf --from-literal=dbpassword=1q2w3e
# где :
# generic это тип секрета(всего 3) это generic-пароли/токены приложения, docker-registry=данные авторизации в docker-registry
# и tls = tls сертификаты для Ingress
# test = это название серекрета
# --from-literal это опции  здесь test это ключ а asdf это значение так и со вторым --from-literal
# 

