---
# Манифест нашего PersistentVolume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fileshare
spec:
  storageClassName: standard #csi-ceph-hdd-ms1 # это имя зависит от стораджей в кубернетесе
  accessModes:
  - ReadWriteMany # 
  resources:
    requests:
      storage: 100Mi

# Чтоб посмотреть какие стораджи есть в кластере необходимо выполнить команду kubectl get sc она выведит всю инфу с именами и далее в файл pvc.yaml указываем нужный сторадж
# 
