---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-env
data:
  dbhost: postgresql
  DEBUG: "false"
...


# Данный конфиг файл помогает стандартизировать переменные окружения передаваемые подам
# если в дальнейшем мы поменяем, добавим или изменим переменную то 
# она автоматичеески будет дотсупна тем подам которые используют данный конфиг файл
# также чтоб применить данный конфиг необходимо выполнить данную команду

# kubectl.exe apply -f и путь до файла configmap.yaml

# Но после изменения данного файла контейнеры не смогут автоматически получить новые/измененные данные они будут работать 
# со старыми значениями 
# чтоб все контейнеры получили новые значения их надо убивать и запускать заново
