---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        env: # а эти переменные будут доступны только поду и его репликам  с именем  my-deployment
        - name: TEST
          value: foo
        envFrom: # Вот тут мы передаем файл конфиг мап, который ранее мы применили apply
        - configMapRef:
            name: my-configmap-env  # сюда передаем name из конфиг мапа
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
...

# Для того чтоб использовать configmap нам необходимо передать его поду 
# если все окей, то по команде kubectl describe deployment.apps покажет нам вот такую строку
#Environment Variables from:
#      my-configmap-env  ConfigMap  Optional: false 

# для того чтоб посмотреть что в данном файле находиться можно, либу руками посмотреть что есть в ней если есть доступ к нему
# либо командой 
# kubectl cm my-configmap-env (name из файла) -o  yaml
# либо командой kubectl.exe exec -it имя контейнера -- env



